/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ie.view;

import ie.dao.FuncionarioDAO;
import ie.model.Funcionario;
import ie.model.Utilitarios;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author mrs_a
 */
public class GerenciarFuncionarios extends javax.swing.JPanel {

//Metodo listar Funcionarios
    public void listarFuncionarios() {
        FuncionarioDAO dao = new FuncionarioDAO();
        List<Funcionario> lista = dao.listarFuncionario();
        DefaultTableModel dados = (DefaultTableModel) jT_funcionario.getModel();
        dados.setNumRows(0);
        for (Funcionario c : lista) {
            dados.addRow(new Object[]{
                c.getId_funcionario(),
                c.getNome(),
                c.getCriado(),
                c.getModificado()});
        }
    }

    public GerenciarFuncionarios() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jT_funcionario = new javax.swing.JTable();
        txt_nomeFuncionario = new javax.swing.JTextField();
        txt_idFuncionario = new javax.swing.JTextField();
        btn_novoFuncionario = new javax.swing.JLabel();
        btn_alterarFuncionario = new javax.swing.JLabel();
        btn_excluirFuncionario = new javax.swing.JLabel();
        btn_limparFuncionario = new javax.swing.JLabel();

        jT_funcionario.setAutoCreateRowSorter(true);
        jT_funcionario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "id_cliente", "Nome", "Criado", "Modificado"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jT_funcionario.setToolTipText("Duplo clicke no registro para alterá-lo!");
        jT_funcionario.setFocusable(false);
        jT_funcionario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jT_funcionarioMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jT_funcionario);
        if (jT_funcionario.getColumnModel().getColumnCount() > 0) {
            jT_funcionario.getColumnModel().getColumn(0).setMinWidth(0);
            jT_funcionario.getColumnModel().getColumn(0).setPreferredWidth(0);
            jT_funcionario.getColumnModel().getColumn(0).setMaxWidth(0);
            jT_funcionario.getColumnModel().getColumn(1).setResizable(false);
            jT_funcionario.getColumnModel().getColumn(1).setPreferredWidth(300);
        }

        txt_nomeFuncionario.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_nomeFuncionario.setToolTipText("Pesquisa");
        txt_nomeFuncionario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_nomeFuncionarioKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_nomeFuncionarioKeyTyped(evt);
            }
        });

        txt_idFuncionario.setBackground(new java.awt.Color(255, 255, 255, 0));
        txt_idFuncionario.setForeground(new java.awt.Color(63, 63, 63));
        txt_idFuncionario.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_idFuncionario.setBorder(null);
        txt_idFuncionario.setEnabled(false);
        txt_idFuncionario.setFocusable(false);
        txt_idFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_idFuncionarioActionPerformed(evt);
            }
        });

        btn_novoFuncionario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ie/img/adicionar32_orig.png"))); // NOI18N
        btn_novoFuncionario.setEnabled(false);
        btn_novoFuncionario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_novoFuncionarioMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_novoFuncionarioMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_novoFuncionarioMouseExited(evt);
            }
        });

        btn_alterarFuncionario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ie/img/editar32_orig.png"))); // NOI18N
        btn_alterarFuncionario.setEnabled(false);
        btn_alterarFuncionario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_alterarFuncionarioMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_alterarFuncionarioMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_alterarFuncionarioMouseExited(evt);
            }
        });

        btn_excluirFuncionario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ie/img/excluir32_orig.png"))); // NOI18N
        btn_excluirFuncionario.setEnabled(false);
        btn_excluirFuncionario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_excluirFuncionarioMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_excluirFuncionarioMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_excluirFuncionarioMouseExited(evt);
            }
        });

        btn_limparFuncionario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ie/img/limpar32_orig.png"))); // NOI18N
        btn_limparFuncionario.setEnabled(false);
        btn_limparFuncionario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_limparFuncionarioMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_limparFuncionarioMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_limparFuncionarioMouseExited(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txt_idFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(txt_nomeFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addComponent(btn_novoFuncionario)
                        .addGap(18, 18, 18)
                        .addComponent(btn_alterarFuncionario)
                        .addGap(18, 18, 18)
                        .addComponent(btn_excluirFuncionario)
                        .addGap(18, 18, 18)
                        .addComponent(btn_limparFuncionario)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(txt_idFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_nomeFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_novoFuncionario)
                    .addComponent(btn_alterarFuncionario)
                    .addComponent(btn_excluirFuncionario)
                    .addComponent(btn_limparFuncionario))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 354, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jT_funcionarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jT_funcionarioMouseClicked

        jT_funcionario.addMouseListener(new MouseAdapter() {
            public void mouseClicked(MouseEvent e) {
                if (e.getClickCount() == 2) {
                    txt_idFuncionario.setText(jT_funcionario.getValueAt(jT_funcionario.getSelectedRow(), 0).toString());
                    txt_nomeFuncionario.setText(jT_funcionario.getValueAt(jT_funcionario.getSelectedRow(), 1).toString());

                    //desabilita botões
                    btn_novoFuncionario.setEnabled(false);
                    btn_alterarFuncionario.setEnabled(true);
                    btn_excluirFuncionario.setEnabled(true);
                    btn_limparFuncionario.setEnabled(true);

                }
            }
        });
    }//GEN-LAST:event_jT_funcionarioMouseClicked

    private void txt_nomeFuncionarioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_nomeFuncionarioKeyPressed
        if ("".equals(txt_idFuncionario.getText())) {
            btn_novoFuncionario.setEnabled(true);
            btn_alterarFuncionario.setEnabled(false);
            btn_excluirFuncionario.setEnabled(false);
            btn_limparFuncionario.setEnabled(true);
        }
    }//GEN-LAST:event_txt_nomeFuncionarioKeyPressed

    private void txt_nomeFuncionarioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_nomeFuncionarioKeyTyped

        String caracteres = "ABCDEFGHIJKLMNOPQRSTUVWXYZ0987654321-_";
        char keyChar = evt.getKeyChar();

        if (Character.isLetter(keyChar)) {
            keyChar = Character.toUpperCase(keyChar);
            evt.setKeyChar(keyChar);
        } else if (!caracteres.contains(Character.toUpperCase(keyChar) + "")) {
            evt.consume();
        }
    }//GEN-LAST:event_txt_nomeFuncionarioKeyTyped

    private void txt_idFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_idFuncionarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_idFuncionarioActionPerformed

    private void btn_novoFuncionarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_novoFuncionarioMouseClicked

// Criar novo registro Funcionario
        if (btn_novoFuncionario.isEnabled()) {

            Utilitarios dh = new Utilitarios();
            String dataHora = dh.DH();

            Funcionario obj = new Funcionario();

            obj.setNome(txt_nomeFuncionario.getText());
            obj.setCriado(dataHora);
            obj.setModificado(dataHora);

            FuncionarioDAO dao = new FuncionarioDAO();
            dao.CadastrarFuncionario(obj);

            txt_idFuncionario.setText("");
            txt_nomeFuncionario.setText("");

            btn_novoFuncionario.setEnabled(false);
            btn_alterarFuncionario.setEnabled(false);
            btn_excluirFuncionario.setEnabled(false);
            btn_limparFuncionario.setEnabled(false);

            listarFuncionarios();
        }

    }//GEN-LAST:event_btn_novoFuncionarioMouseClicked

    private void btn_alterarFuncionarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_alterarFuncionarioMouseClicked

        // Alterar novo registro Funcionario
        if (btn_alterarFuncionario.isEnabled()) {

            Utilitarios dh = new Utilitarios();
            String dataHora = dh.DH();

            Funcionario obj = new Funcionario();

            obj.setNome(txt_nomeFuncionario.getText());
            obj.setCriado(jT_funcionario.getValueAt(jT_funcionario.getSelectedRow(), 2).toString());
            obj.setModificado(dataHora);
            obj.setId_funcionario(Integer.parseInt(txt_idFuncionario.getText()));

            FuncionarioDAO dao = new FuncionarioDAO();
            dao.alterarFuncionario(obj);

            txt_idFuncionario.setText("");
            txt_nomeFuncionario.setText("");

            btn_novoFuncionario.setEnabled(false);
            btn_alterarFuncionario.setEnabled(false);
            btn_excluirFuncionario.setEnabled(false);
            btn_limparFuncionario.setEnabled(false);

            listarFuncionarios();
        }

    }//GEN-LAST:event_btn_alterarFuncionarioMouseClicked

    private void btn_excluirFuncionarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_excluirFuncionarioMouseClicked

// botao Excluir Funcionarios
        if (btn_excluirFuncionario.isEnabled()) {

            Funcionario obj = new Funcionario();

            obj.setId_funcionario(Integer.parseInt(txt_idFuncionario.getText()));

            FuncionarioDAO dao = new FuncionarioDAO();

            dao.excluirFuncionario(obj);

            //Limpa os paineis
            txt_idFuncionario.setText("");
            txt_nomeFuncionario.setText("");

            //desabilita botões
            btn_novoFuncionario.setEnabled(false);
            btn_alterarFuncionario.setEnabled(false);
            btn_excluirFuncionario.setEnabled(false);
            btn_limparFuncionario.setEnabled(false);

            listarFuncionarios();
        }

    }//GEN-LAST:event_btn_excluirFuncionarioMouseClicked

    private void btn_limparFuncionarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_limparFuncionarioMouseClicked

        if (btn_limparFuncionario.isEnabled()) {

            txt_idFuncionario.setText("");
            txt_nomeFuncionario.setText("");

            btn_novoFuncionario.setEnabled(false);
            btn_alterarFuncionario.setEnabled(false);
            btn_excluirFuncionario.setEnabled(false);
            btn_limparFuncionario.setEnabled(false);
        }

    }//GEN-LAST:event_btn_limparFuncionarioMouseClicked

    private void btn_novoFuncionarioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_novoFuncionarioMouseEntered

        btn_novoFuncionario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ie/img/adicionar32_sat.png")));

    }//GEN-LAST:event_btn_novoFuncionarioMouseEntered

    private void btn_novoFuncionarioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_novoFuncionarioMouseExited

        btn_novoFuncionario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ie/img/adicionar32_orig.png")));

    }//GEN-LAST:event_btn_novoFuncionarioMouseExited

    private void btn_alterarFuncionarioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_alterarFuncionarioMouseEntered

        btn_alterarFuncionario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ie/img/editar32_sat.png")));

    }//GEN-LAST:event_btn_alterarFuncionarioMouseEntered

    private void btn_alterarFuncionarioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_alterarFuncionarioMouseExited

        btn_alterarFuncionario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ie/img/editar32_orig.png")));

    }//GEN-LAST:event_btn_alterarFuncionarioMouseExited

    private void btn_excluirFuncionarioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_excluirFuncionarioMouseEntered

        btn_excluirFuncionario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ie/img/excluir32_sat.png")));

    }//GEN-LAST:event_btn_excluirFuncionarioMouseEntered

    private void btn_excluirFuncionarioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_excluirFuncionarioMouseExited

        btn_excluirFuncionario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ie/img/excluir32_orig.png")));

    }//GEN-LAST:event_btn_excluirFuncionarioMouseExited

    private void btn_limparFuncionarioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_limparFuncionarioMouseEntered

        btn_limparFuncionario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ie/img/limpar32_sat.png")));

    }//GEN-LAST:event_btn_limparFuncionarioMouseEntered

    private void btn_limparFuncionarioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_limparFuncionarioMouseExited

        btn_limparFuncionario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ie/img/limpar32_orig.png")));

    }//GEN-LAST:event_btn_limparFuncionarioMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btn_alterarFuncionario;
    private javax.swing.JLabel btn_excluirFuncionario;
    private javax.swing.JLabel btn_limparFuncionario;
    private javax.swing.JLabel btn_novoFuncionario;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jT_funcionario;
    private javax.swing.JTextField txt_idFuncionario;
    private javax.swing.JTextField txt_nomeFuncionario;
    // End of variables declaration//GEN-END:variables
}
