/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ie.view;

import ie.dao.ClienteDAO;
import ie.model.Cliente;
import ie.model.Utilitarios;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author mrs_a
 */
public class GerenciarClientes extends javax.swing.JPanel {

//Metodo listar Clientes
    public void listarClientes() {
        ClienteDAO dao = new ClienteDAO();
        List<Cliente> lista = dao.listarCliente();
        DefaultTableModel dados = (DefaultTableModel) jT_cliente.getModel();
        dados.setNumRows(0);
        for (Cliente c : lista) {
            dados.addRow(new Object[]{
                c.getId_cliente(),
                c.getNome(),
                c.getCriado(),
                c.getModificado()});
        }
    }

    public GerenciarClientes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jT_cliente = new javax.swing.JTable();
        txt_nomeCliente = new javax.swing.JTextField();
        txt_idCliente = new javax.swing.JTextField();
        btn_novoCliente = new javax.swing.JLabel();
        btn_alterarCliente = new javax.swing.JLabel();
        btn_excluirCliente = new javax.swing.JLabel();
        btn_limparCliente = new javax.swing.JLabel();

        jT_cliente.setAutoCreateRowSorter(true);
        jT_cliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "id_cliente", "Nome", "Criado", "Modificado"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jT_cliente.setToolTipText("Duplo clicke no registro para alterá-lo!");
        jT_cliente.setFocusable(false);
        jT_cliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jT_clienteMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jT_cliente);
        if (jT_cliente.getColumnModel().getColumnCount() > 0) {
            jT_cliente.getColumnModel().getColumn(0).setMinWidth(0);
            jT_cliente.getColumnModel().getColumn(0).setPreferredWidth(0);
            jT_cliente.getColumnModel().getColumn(0).setMaxWidth(0);
            jT_cliente.getColumnModel().getColumn(1).setResizable(false);
            jT_cliente.getColumnModel().getColumn(1).setPreferredWidth(300);
        }

        txt_nomeCliente.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_nomeCliente.setToolTipText("Pesquisa");
        txt_nomeCliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_nomeClienteKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_nomeClienteKeyTyped(evt);
            }
        });

        txt_idCliente.setBackground(new java.awt.Color(255, 255, 255, 0));
        txt_idCliente.setForeground(new java.awt.Color(63, 63, 63));
        txt_idCliente.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_idCliente.setBorder(null);
        txt_idCliente.setEnabled(false);
        txt_idCliente.setFocusable(false);

        btn_novoCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ie/img/adicionar32_orig.png"))); // NOI18N
        btn_novoCliente.setEnabled(false);
        btn_novoCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_novoClienteMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_novoClienteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_novoClienteMouseExited(evt);
            }
        });

        btn_alterarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ie/img/editar32_orig.png"))); // NOI18N
        btn_alterarCliente.setEnabled(false);
        btn_alterarCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_alterarClienteMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_alterarClienteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_alterarClienteMouseExited(evt);
            }
        });

        btn_excluirCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ie/img/excluir32_orig.png"))); // NOI18N
        btn_excluirCliente.setEnabled(false);
        btn_excluirCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_excluirClienteMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_excluirClienteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_excluirClienteMouseExited(evt);
            }
        });

        btn_limparCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ie/img/limpar32_orig.png"))); // NOI18N
        btn_limparCliente.setEnabled(false);
        btn_limparCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_limparClienteMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_limparClienteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_limparClienteMouseExited(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 593, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txt_idCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(txt_nomeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_novoCliente)
                        .addGap(18, 18, 18)
                        .addComponent(btn_alterarCliente)
                        .addGap(18, 18, 18)
                        .addComponent(btn_excluirCliente)
                        .addGap(18, 18, 18)
                        .addComponent(btn_limparCliente)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(txt_idCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_nomeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_novoCliente)
                    .addComponent(btn_alterarCliente)
                    .addComponent(btn_excluirCliente)
                    .addComponent(btn_limparCliente))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 354, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jT_clienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jT_clienteMouseClicked

        jT_cliente.addMouseListener(new MouseAdapter() {
            public void mouseClicked(MouseEvent e) {
                if (e.getClickCount() == 2) {
                    txt_idCliente.setText(jT_cliente.getValueAt(jT_cliente.getSelectedRow(), 0).toString());
                    txt_nomeCliente.setText(jT_cliente.getValueAt(jT_cliente.getSelectedRow(), 1).toString());

                    //desabilita botões
                    btn_novoCliente.setEnabled(false);
                    btn_alterarCliente.setEnabled(true);
                    btn_excluirCliente.setEnabled(true);
                    btn_limparCliente.setEnabled(true);

                }
            }
        });
    }//GEN-LAST:event_jT_clienteMouseClicked

    private void txt_nomeClienteKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_nomeClienteKeyPressed
        if ("".equals(txt_idCliente.getText())) {
            btn_novoCliente.setEnabled(true);
            btn_alterarCliente.setEnabled(false);
            btn_excluirCliente.setEnabled(false);
            btn_limparCliente.setEnabled(true);
        }
    }//GEN-LAST:event_txt_nomeClienteKeyPressed

    private void txt_nomeClienteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_nomeClienteKeyTyped

        String caracteres = "ABCDEFGHIJKLMNOPQRSTUVWXYZ0987654321-_";
        char keyChar = evt.getKeyChar();

        if (Character.isLetter(keyChar)) {
            keyChar = Character.toUpperCase(keyChar);
            evt.setKeyChar(keyChar);
        } else if (!caracteres.contains(Character.toUpperCase(keyChar) + "")) {
            evt.consume();
        }
    }//GEN-LAST:event_txt_nomeClienteKeyTyped

    private void btn_novoClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_novoClienteMouseClicked

// Criar novo registro Cliente
        if (btn_novoCliente.isEnabled()) {

            Utilitarios dh = new Utilitarios();
            String dataHora = dh.DH();

            Cliente obj = new Cliente();

            obj.setNome(txt_nomeCliente.getText());
            obj.setCriado(dataHora);
            obj.setModificado(dataHora);

            ClienteDAO dao = new ClienteDAO();
            dao.CadastrarCliente(obj);

            txt_idCliente.setText("");
            txt_nomeCliente.setText("");

            btn_novoCliente.setEnabled(false);
            btn_alterarCliente.setEnabled(false);
            btn_excluirCliente.setEnabled(false);
            btn_limparCliente.setEnabled(false);

            listarClientes();
        }

    }//GEN-LAST:event_btn_novoClienteMouseClicked

    private void btn_alterarClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_alterarClienteMouseClicked

        // Alterar novo registro Cliente
        if (btn_alterarCliente.isEnabled()) {

            Utilitarios dh = new Utilitarios();
            String dataHora = dh.DH();

            Cliente obj = new Cliente();

            obj.setNome(txt_nomeCliente.getText());
            obj.setCriado(jT_cliente.getValueAt(jT_cliente.getSelectedRow(), 2).toString());
            obj.setModificado(dataHora);
            obj.setId_cliente(Integer.parseInt(txt_idCliente.getText()));

            ClienteDAO dao = new ClienteDAO();
            dao.alterarCliente(obj);

            txt_idCliente.setText("");
            txt_nomeCliente.setText("");

            btn_novoCliente.setEnabled(false);
            btn_alterarCliente.setEnabled(false);
            btn_excluirCliente.setEnabled(false);
            btn_limparCliente.setEnabled(false);

            listarClientes();
        }

    }//GEN-LAST:event_btn_alterarClienteMouseClicked

    private void btn_excluirClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_excluirClienteMouseClicked

// botao Excluir Clientes
        if (btn_excluirCliente.isEnabled()) {

 int resposta = JOptionPane.showConfirmDialog(
                    null,
                    "Todos os registros cadastrados com " + txt_nomeCliente.getText() + " serão apagados. Continuar?",
                    "Confirmação",
                    JOptionPane.YES_NO_OPTION,
                    JOptionPane.WARNING_MESSAGE
            );
            if (resposta == JOptionPane.YES_OPTION) {

            Cliente obj = new Cliente();

            obj.setId_cliente(Integer.parseInt(txt_idCliente.getText()));

            ClienteDAO dao = new ClienteDAO();

            dao.excluirCliente(obj);

            //Limpa os paineis
            txt_idCliente.setText("");
            txt_nomeCliente.setText("");

            //desabilita botões
            btn_novoCliente.setEnabled(false);
            btn_alterarCliente.setEnabled(false);
            btn_excluirCliente.setEnabled(false);
            btn_limparCliente.setEnabled(false);

            listarClientes();
        }
}

    }//GEN-LAST:event_btn_excluirClienteMouseClicked

    private void btn_limparClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_limparClienteMouseClicked

        if (btn_limparCliente.isEnabled()) {

            txt_idCliente.setText("");
            txt_nomeCliente.setText("");

            btn_novoCliente.setEnabled(false);
            btn_alterarCliente.setEnabled(false);
            btn_excluirCliente.setEnabled(false);
            btn_limparCliente.setEnabled(false);
        }

    }//GEN-LAST:event_btn_limparClienteMouseClicked

    private void btn_novoClienteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_novoClienteMouseEntered

        btn_novoCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ie/img/adicionar32_sat.png")));

    }//GEN-LAST:event_btn_novoClienteMouseEntered

    private void btn_novoClienteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_novoClienteMouseExited

        btn_novoCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ie/img/adicionar32_orig.png")));

    }//GEN-LAST:event_btn_novoClienteMouseExited

    private void btn_alterarClienteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_alterarClienteMouseEntered

        btn_alterarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ie/img/editar32_sat.png")));

    }//GEN-LAST:event_btn_alterarClienteMouseEntered

    private void btn_alterarClienteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_alterarClienteMouseExited

        btn_alterarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ie/img/editar32_orig.png")));

    }//GEN-LAST:event_btn_alterarClienteMouseExited

    private void btn_excluirClienteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_excluirClienteMouseEntered

        btn_excluirCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ie/img/excluir32_sat.png")));

    }//GEN-LAST:event_btn_excluirClienteMouseEntered

    private void btn_excluirClienteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_excluirClienteMouseExited

        btn_excluirCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ie/img/excluir32_orig.png")));

    }//GEN-LAST:event_btn_excluirClienteMouseExited

    private void btn_limparClienteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_limparClienteMouseEntered

        btn_limparCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ie/img/limpar32_sat.png")));

    }//GEN-LAST:event_btn_limparClienteMouseEntered

    private void btn_limparClienteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_limparClienteMouseExited

        btn_limparCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ie/img/limpar32_orig.png")));

    }//GEN-LAST:event_btn_limparClienteMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btn_alterarCliente;
    private javax.swing.JLabel btn_excluirCliente;
    private javax.swing.JLabel btn_limparCliente;
    private javax.swing.JLabel btn_novoCliente;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jT_cliente;
    private javax.swing.JTextField txt_idCliente;
    private javax.swing.JTextField txt_nomeCliente;
    // End of variables declaration//GEN-END:variables
}
