/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package ie.view;

import ie.dao.ClienteDAO;
import ie.dao.FuncionarioDAO;
import ie.dao.IndicadorDAO;
import ie.model.Cliente;
import ie.model.Funcionario;
import ie.model.Indicador;
import ie.model.Utilitarios;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author gmg
 */
public class NovoRegistro extends javax.swing.JDialog {

    //Metodo alterar icone do calendario
    public void SetIconCalendar() {

        jd_data.getCalendarButton().setIcon(
                new ImageIcon(getClass().getResource("/ie/img/calendario24_orig.png"))
        );

    }

//Metodo Atualiza cb_cliente
    public void AtualizarcbClientes() {
        ClienteDAO dao = new ClienteDAO();
        List<Cliente> lista = dao.listarCliente();

        cb_cliente.removeAllItems();
        cb_cliente.addItem("");

        for (Cliente c : lista) {
            cb_cliente.addItem(c.getNome());

        }
    }

//Metodo Atualiza cb_designer
    public void AtualizarcbDesigner() {
        FuncionarioDAO dao = new FuncionarioDAO();
        List<Funcionario> lista = dao.listarFuncionario();

        cb_designer.removeAllItems();
        cb_designer.addItem("");

        for (Funcionario c : lista) {
            cb_designer.addItem(c.getNome());

        }
    }

//Metodo Aponta id Cliente
    public int ApontaIdCliente() {
        int id = 0;

        ClienteDAO dao = new ClienteDAO();
        List<Cliente> lista = dao.RetornaId_cliente(cb_cliente.getSelectedItem().toString());

        for (Cliente c : lista) {
            id = c.getId_cliente();

        }
        return id;
    }

//Metodo Aponta id Designer
    public int ApontaIdDesigner() {
        int id = 0;

        FuncionarioDAO dao = new FuncionarioDAO();
        List<Funcionario> lista = dao.RetornaId(cb_designer.getSelectedItem().toString());

        for (Funcionario c : lista) {
            id = c.getId_funcionario();

        }
        return id;
    }

    public NovoRegistro(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        SetIconCalendar();
        this.setLocationRelativeTo(null);

        AtualizarcbClientes();
        AtualizarcbDesigner();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        cb_designer = new javax.swing.JComboBox<>();
        lb_designer = new javax.swing.JLabel();
        txt_pedido = new javax.swing.JTextField();
        lb_pedido = new javax.swing.JLabel();
        txt_numArtes = new javax.swing.JTextField();
        lb_numArtes = new javax.swing.JLabel();
        cb_status = new javax.swing.JComboBox<>();
        lb_status = new javax.swing.JLabel();
        lb_cliente = new javax.swing.JLabel();
        cb_cliente = new javax.swing.JComboBox<>();
        lb_data = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jd_data = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Novo Registro");
        setMinimumSize(new java.awt.Dimension(212, 255));
        setResizable(false);
        setSize(new java.awt.Dimension(212, 255));

        lb_designer.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        lb_designer.setText("Designer");

        txt_pedido.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        lb_pedido.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        lb_pedido.setText("Pedido");

        txt_numArtes.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        lb_numArtes.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        lb_numArtes.setText("Nº Artes");

        cb_status.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Aprovado", "Reprovado" }));

        lb_status.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        lb_status.setText("Status");

        lb_cliente.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        lb_cliente.setText("Cliente");

        lb_data.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        lb_data.setText("Data");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ie/img/salvar32_orig.png"))); // NOI18N
        jLabel2.setToolTipText("Salvar");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel2MouseExited(evt);
            }
        });

        jd_data.setDateFormatString("yyyy/MM/dd");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jd_data, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lb_data))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(lb_designer)
                                .addComponent(cb_designer, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txt_pedido, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lb_pedido)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(lb_numArtes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txt_numArtes, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(18, 18, 18)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lb_status)
                                        .addComponent(cb_status, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                            .addComponent(lb_cliente)
                            .addComponent(cb_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lb_designer)
                .addGap(0, 0, 0)
                .addComponent(cb_designer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lb_pedido)
                .addGap(0, 0, 0)
                .addComponent(txt_pedido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lb_numArtes)
                        .addGap(0, 0, 0)
                        .addComponent(txt_numArtes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lb_status)
                        .addGap(0, 0, 0)
                        .addComponent(cb_status, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lb_cliente)
                .addGap(0, 0, 0)
                .addComponent(cb_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lb_data)
                        .addGap(0, 0, 0)
                        .addComponent(jd_data, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel2))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseEntered

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ie/img/salvar32_sat.png")));

    }//GEN-LAST:event_jLabel2MouseEntered

    private void jLabel2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseExited

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ie/img/salvar32_orig.png")));

    }//GEN-LAST:event_jLabel2MouseExited

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked

        if ("".equals(txt_pedido.getText())) {
            JOptionPane.showMessageDialog(null, "Número do Pedido Inválido!", "", 2);
        } else {
            if ("".equals(txt_numArtes.getText())) {
                JOptionPane.showMessageDialog(null, "Número de artes Inválido!", "", 2);
            } else {
                if (jd_data.getDate() == null) {
                    JOptionPane.showMessageDialog(null, "Data Iválida!", "", 2);
                } else {
                    if ("".equals(cb_designer.getSelectedItem().toString())) {
                        JOptionPane.showMessageDialog(null, "Designer Iválido!", "", 2);
                    } else {
                        if ("".equals(cb_cliente.getSelectedItem().toString())) {
                            JOptionPane.showMessageDialog(null, "Cliente Iválido!", "", 2);
                        } else {
                            if ("".equals(cb_status.getSelectedItem().toString())) {
                                JOptionPane.showMessageDialog(null, "Status Iválido!", "", 2);
                            } else {

                                Utilitarios dh = new Utilitarios();
                                String dataHora = dh.DH();

                                int idcliente = ApontaIdCliente();
                                int idDesigner = ApontaIdDesigner();
                                Date dataSelecionada = jd_data.getDate();
                                // Formata a data como YYYY/MM/DD
                                SimpleDateFormat formato = new SimpleDateFormat("yyyy/MM/dd");
                                String dataFormatada = formato.format(dataSelecionada);

                                Indicador obj = new Indicador();

                                obj.setPedido(txt_pedido.getText());
                                obj.setQtd_artes(Integer.parseInt(txt_numArtes.getText()));
                                obj.setId_cliente(idcliente);
                                obj.setId_funcionario(idDesigner);
                                obj.setStatus(cb_status.getSelectedItem().toString());
                                obj.setData(dataFormatada);
                                obj.setCriado(dataHora);
                                obj.setModificado(dataHora);
                                //JOptionPane.showMessageDialog(null, dataFormatada, "", 2);

                                IndicadorDAO dao = new IndicadorDAO();
                                dao.cadastrarIndicador(obj);

                                this.dispose();

                            }
                        }
                    }
                }
            }
        }


    }//GEN-LAST:event_jLabel2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NovoRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NovoRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NovoRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NovoRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                NovoRegistro dialog = new NovoRegistro(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cb_cliente;
    private javax.swing.JComboBox<String> cb_designer;
    private javax.swing.JComboBox<String> cb_status;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private com.toedter.calendar.JDateChooser jd_data;
    private javax.swing.JLabel lb_cliente;
    private javax.swing.JLabel lb_data;
    private javax.swing.JLabel lb_designer;
    private javax.swing.JLabel lb_numArtes;
    private javax.swing.JLabel lb_pedido;
    private javax.swing.JLabel lb_status;
    private javax.swing.JTextField txt_numArtes;
    private javax.swing.JTextField txt_pedido;
    // End of variables declaration//GEN-END:variables
}
